<?php
    namespace NodeJS_Chat;

    $localHost = Settings::get('dev_mode') === true ? 'http://localhost' : Settings::get('host');
?>
<!DOCTYPE html>
<html>
<head>
    <title><?=Localization::get('chatTitle1')?></title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="css/chat.css?v=5" />

    <script src="<?=$localHost?>:8090/socket.io/socket.io.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="js/jquery.cookie.js"></script>
    <script src="js/front.js?v=3"></script>
</head>

<body>
<div class="msg-window">
    <h1>
        <?=Localization::get('chatTitle1')?>

        <div class="r-actions">
            <input type="text" name="iChangeNick" placeholder="<?=Localization::get('newNick')?>">
            <button class="change-nick js-change-nick"><?=Localization::get('changeNick')?></button>
            <button class="clear-window"><?=Localization::get('clearHistory')?></button>
        </div>
    </h1>

    <div class="nick">
        <h2><?=Localization::get('welcomePleaseIntroduceYourself')?></h2>
        <input type="text" name="nick" placeholder="<?=Localization::get('yourNameOrNick')?>" />

        <button class="connect" data-role="chat-connect"><?=Localization::get('connect')?></button>
    </div>

    <div class="container"></div>
    <div class="msg-btm">
        <div class="msg-input-cnt">
            <input type="text" name="msg-input" placeholder="<?=Localization::get('yourMessage')?>">
            <span class="smiles-cnt-opener"></span>
            <div class="smiles-cnt">
                <span title=":)" class="smiley sm1"></span>
                <span title=":D" class="smiley sm2"></span>
                <span title=";)" class="smiley sm3"></span>
                <span title="xD" class="smiley sm4"></span>
                <span title=":-D" class="smiley sm5"></span>
                <span title="O_O" class="smiley sm6"></span>
                <span title="^_^" class="smiley sm7"></span>
                <span title=":~D" class="smiley sm8"></span>
                <span title=":-X" class="smiley sm9"></span>
            </div>
        </div>
        <button name="submitMessage"><?=Localization::get('send')?></button>
    </div>
</div>

<div class="users">
    <div>
        <p><?=Localization::get('usersList')?></p>
    </div>

    <div class="users-container"></div>
</div>
</body>
</html>