<?php
    $localHost = $settings['dev_mode'] === true ? 'http://localhost' : $settings['host'];
?>
<!DOCTYPE html>
<html>
<head>
    <title>ЖК "Гринландия" - Чат</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="chat.css" />

    <script src="<?=$localHost?>:8090/socket.io/socket.io.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="js/jquery.cookie.js"></script>
    <script src="front.js"></script>
</head>

<body>
<div class="msg-window">
    <h1>
        ЖК "Гринландия" - Чат

        <div class="r-actions">
            <input type="text" name="iChangeNick" placeholder="Новый ник">
            <button class="change-nick js-change-nick">Изменить ник</button>
            <button class="clear-window">Очистить историю</button>
        </div>
    </h1>

    <div class="nick">
        <h2>Добро пожаловать. Пожалуйста представьтесь.</h2>
        <input type="text" name="nick" placeholder="Ваше имя или ник" />

        <button class="connect" data-role="chat-connect">Присоединиться</button>
    </div>

    <div class="container"></div>
    <div class="msg-btm">
        <div class="msg-input-cnt">
            <input type="text" name="msg-input" placeholder="Ваше сообщение">
            <span class="smiles-cnt-opener"></span>
            <div class="smiles-cnt">
                <span title=":)" class="smiley sm1"></span>
                <span title=":D" class="smiley sm2"></span>
                <span title=";)" class="smiley sm3"></span>
                <span title="xD" class="smiley sm4"></span>
                <span title=":-D" class="smiley sm5"></span>
                <span title="O_O" class="smiley sm6"></span>
                <span title="^_^" class="smiley sm7"></span>
                <span title=":~D" class="smiley sm8"></span>
                <span title=":-X" class="smiley sm9"></span>
            </div>
        </div>
        <button name="submitMessage">Отправить</button>
    </div>
</div>

<div class="users">
    <div>
        <p>Список пользователей:</p>
    </div>

    <div class="users-container"></div>
</div>
</body>
</html>